solarwinds/apm-js

.github/workflows/checks.yml
.yarnrc.yml
package.json
packages/eslint-config/package.json
packages/sdk/src/cache.ts
packages/sdk/src/inbound-metrics-processor.ts
packages/sdk/src/parent-info-processor.ts
yarn.lock

Replaces the `setXyz` APIs with a `getOrInit` method returning a reference to the cache entry which can then be operated on directly. Sadly I wasn't able to get rid of the singleton architecture since it would make the custom transaction name API very unwieldy.

Cache API cleanup

---

.yarn/versions/35ebe116.yml
CONTRIBUTING.md
examples/fastify-postgres/package.json
examples/hello-distributed/package.json
examples/next-prisma/package.json
examples/next-prisma/prisma/schema.prisma
examples/next-prisma/tsconfig.json
package.json
packages/bindings/package.json
packages/compat/package.json
packages/dependencies/package.json
packages/eslint-config/package.json
packages/histogram/package.json
packages/lazy/package.json
packages/merged-config/package.json
packages/sdk/package.json
packages/solarwinds-apm/package.json
packages/test/package.json
yarn.lock

Updating the Prisma instrumentation in the examples removes vulnerable instrumentation packages from anywhere in the repo dependency tree (it's already explicitly disallowed by all the published packages)

Bump deps and remove unused Yarn PnP stuff

---

packages/bindings/npm/linux-arm64-gnu/package.json
packages/bindings/npm/linux-arm64-musl/package.json
packages/bindings/npm/linux-x64-gnu/package.json
packages/bindings/npm/linux-x64-musl/package.json
packages/bindings/package.json
packages/compat/package.json
packages/dependencies/package.json
packages/eslint-config/package.json
packages/histogram/package.json
packages/lazy/package.json
packages/merged-config/package.json
packages/sdk/package.json
packages/solarwinds-apm/package.json
packages/test/package.json

Mostly so I can test the proxy on both this library and the legacy on at the same time tomorrow
@solarwinds-apm/bindings 1.0.0-pre.2, @solarwinds-apm/compat 1.0.0-pre.2, @solarwinds-apm/dependencies 1.0.0-pre.2, @solarwinds-apm/eslint-config 1.0.0-pre.2, @solarwinds-apm/histogram 1.0.0-pre.2, @solarwinds-apm/lazy 1.0.0-pre.2, @solarwinds-apm/merged-config 1.0.0-pre.2, @solarwinds-apm/sdk 1.0.0-pre.2, @solarwinds-apm/test 1.0.0-pre.1, solarwinds-apm 14.0.0-pre.2

New prerelease

---

.yarn/versions/b53acbb0.yml
packages/solarwinds-apm/src/init.ts

This seems to be required for the Lambda instrumentation to properly flush data but isn't documented anywhere

Provide tracer and meter providers to registered instrumentations

---

.github/workflows/testing.yml
package.json
scripts/testing.js

Useful for testing small changes that require the packages to be present in a registry without publishing a proper npm prerelease

Workflow for publishing testing packages to the Github package registry

---

.github/workflows/checks.yml
.github/workflows/images.yml
docker/16-amazonlinux2.Dockerfile
docker/16-ubi8.Dockerfile
docker/16-ubuntu18.04.Dockerfile
docker/18-amazonlinux.Dockerfile
docker/18-ubi.Dockerfile
docker/18-ubuntu.Dockerfile
docker/20-amazonlinux.Dockerfile
docker/20-ubi.Dockerfile
docker/20-ubuntu.Dockerfile
docker/docker-compose.yml

Adds AmazonLinux 2023 now that it supports `git-lfs`.
nodesource [recently updated](https://github.com/nodesource/distributions?tab=readme-ov-file#new-update-%EF%B8%8F) the way they distribute their Node.js repos, so this PR also addresses that.

Add AmazonLinux 2023 images and update nodesource repo

---

.github/workflows/testing.yml
scripts/testing.js

The GitHub npm registry requires packages to be namespaced with the name of the repository owner, so the workflow now does a bunch of search and replace for that.

Fix testing packages workflow

---

.yarn/versions/36eb5944.yml
packages/sdk/src/diag-logger.ts

Apparently the method is not defined if stdout is not a TTY, which is a bit annoying.

Add TTY check before calling hasColours

---

.yarn/versions/db656d81.yml
packages/solarwinds-apm/src/config.ts
packages/solarwinds-apm/src/init.ts
packages/solarwinds-apm/test/config.test.ts

Also split the OTLP flags between traces and metrics and throw if missing the proper packages for OTLP export instead of silently failing.

Add experimental flags to toggle SW exporters

---

.yarn/versions/ea559484.yml
packages/sdk/src/patches/index.ts
packages/sdk/src/patches/lambda.ts

The instrumentation was submitting broken traces since it picked up a parent span ID from X-Ray for a span that was never sent to use. Fixed by ignoring X-Ray parent propagation.

Fix lambda trace submission

---

.yarn/versions/bcf26f2b.yml
packages/sdk/src/context.ts
packages/sdk/src/inbound-metrics-processor.ts
packages/sdk/src/index.ts
packages/sdk/src/metrics/serverless.ts
packages/sdk/src/response-time-processor.ts
packages/sdk/src/sampler.ts
packages/solarwinds-apm/src/init.ts

Response time OTel metric

---

.yarn/versions/0ac74732.yml
packages/solarwinds-apm/src/config.ts

Reduces cold start a lot, not sure when this was reverted.

Re-disable resource detection by default in Lambda

---

.yarn/versions/cfc065c7.yml
packages/sdk/src/metrics/serverless.ts

Setting an attribute with an undefined value apparently still sends it, just without any attached value. Instead avoid setting any undefined attributes.

Don't send empty http.* attributes in metrics

---

.yarn/versions/e5dca456.yml
packages/eslint-config/index.js
packages/eslint-config/package.json
yarn.lock

Version 7 added native support for the ESLint flat config format we are using, so some things had to be moved around a bit but the config ends up overall simpler.
supersedes #256 & #257

Upgrade to typescript-eslint 7

---

.github/workflows/lambda.yml
.github/workflows/release.yml
.github/workflows/testing.yml
CONTRIBUTING.md
lambda/.gitignore
lambda/.yarnrc.yml
lambda/package.json
lambda/shim.cjs
lambda/wrapper
package.json
scripts/lambda.js
scripts/package.json
yarn.lock

Moves the lambda layer code and CI from `apm-js-lambda` to within this repo with a few tiny changes.
Also now set the `faas.instance` attribute in the wrapper (definitely not copied from Python's)

Move Lambda layer code here

---

.github/dependabot.yml
.yarn/versions/dba65c32.yml
packages/eslint-config/index.js
packages/eslint-config/package.json
packages/sdk/src/metric-exporter.ts
yarn.lock

Realised the config could be made cleaner and also wanted warning for deprecations since the next OTel update deprecates a bunch of things and I'd like to see them clearly in my editor and CI.
Also puts the `typescript-eslint` package in the proper dependabot group.

Simplify ESlint config and warn for deprecations

---

.github/workflows/release.yml
.github/workflows/testing.yml
package.json

It's not necessary and caused some issues since the package names change

Don't lint when publishing testing packages

---

.github/workflows/lambda.yml

Publish prod layers to all regions and make them public. Also use the right ARN.

Support prod layers properly in CI

---

.github/workflows/release.yml
.github/workflows/testing.yml
.gitignore
.yarn/versions/49369b77.yml
.yarnrc.yml
packages/bindings/npm/linux-arm64-gnu-serverless/package.json
packages/bindings/npm/linux-arm64-gnu/package.json
packages/bindings/npm/linux-arm64-musl/package.json
packages/bindings/npm/linux-x64-gnu-serverless/package.json
packages/bindings/npm/linux-x64-gnu/package.json
packages/bindings/npm/linux-x64-musl/package.json
packages/bindings/package.json
packages/compat/package.json
packages/dependencies/package.json
packages/eslint-config/package.json
packages/histogram/package.json
packages/instrumentations/COMPATIBILITY.md
packages/instrumentations/package.json
packages/lazy/package.json
packages/module/package.json
packages/proto/package.json
packages/rollup-config/package.json
packages/sampling/package.json
packages/sdk/package.json
packages/solarwinds-apm/package.json
packages/test/package.json
scripts/publish.js

This makes it so that our published package have [provenance](https://github.blog/2023-04-19-introducing-npm-package-provenance/) information so that customers know they come from us and how they were built. Yarn doesn't support it yet so the workflow is changed to use npm to publish the package archive.

Publish with provenance using npm

---

.yarn/versions/5a072558.yml
packages/instrumentations/src/index.ts
packages/sdk/src/patches/winston.ts
packages/solarwinds-apm/src/config.ts

- Fixes some instrumentations not properly loading in CommonJS by instantiating the main export if it's a class.
- Fixes config validation errors when providing custom instrumentations that don't necessarily extend `InstrumentationBase`
- Fixes new winston instrumentation attempting to use a package that's not installed to export logs via OTel

Small bugfixes

---

.yarn/versions/487a1296.yml
packages/eslint-config/index.js
packages/sampling/package.json
packages/sampling/src/sampler.ts
packages/sampling/src/settings.ts
packages/sampling/src/token-bucket.ts
packages/sampling/test/sampler.test.ts
packages/sampling/test/settings.test.ts
yarn.lock

This implements parent-based sampling logic both for local spans and remote ones with a valid `sw` context.
This also implements core logic for remote and local settings as a prerequisite. The logic for importing settings will live separately (similarly to the new liboboe implementation). At the moment there is also no support for layer names as the feature is not used in any of the OTel based libraries (as far as I know).

Core parent-based sampling logic

---

.yarn/versions/d5e3b4f0.yml
packages/sampling/src/dice.ts
packages/sampling/src/sampler.ts
packages/sampling/src/token-bucket.ts
packages/sampling/src/trace-options.ts
packages/sampling/test/trace-options.test.ts

This is mostly copied over from [the same logic in the trace options propagator](https://github.com/solarwinds/apm-js/blob/main/packages/sdk/src/trace-context-options-propagator.ts).

Trace options parsing

---

.yarn/versions/cbdd5eaf.yml
packages/sampling/src/sampler.ts
packages/sampling/src/settings.ts
packages/sampling/src/trace-options.ts
packages/sampling/test/sampler.test.ts
packages/sampling/test/trace-options.test.ts

This implements the core trigger-tracing logic and tests. It also moves the parent-based code around a bit the the logic remains the same. After this the only remaining piece is the dice roll logic.

Trigger-tracing logic

---

.yarn/versions/eb31c691.yml
packages/sampling/package.json
packages/sampling/src/metrics.ts
packages/sampling/src/sampler.ts
packages/sampling/test/sampler.test.ts
yarn.lock

This implements and tests the sampling counters using OTel-native metrics directly. This also fixes the dice roll fail logic based on the decision tree spec.

Sampling metrics

---

.yarn/versions/19fe8cd4.yml
packages/sampling/src/index.ts
packages/sampling/src/sampler.ts
packages/sampling/src/settings.ts
packages/sampling/src/trace-options.ts
packages/sampling/test/sampler.test.ts

Invalidates settings past their TTL. Also use Uint8Array instead of string to store secret key, because it's returned as binary by the collector and Uint8Array can represent any string but not the opposite.

Handle TTL

---

.github/dependabot.yml
.yarn/versions/19fe8cd4.yml
packages/compat/package.json
packages/compat/test/index.test.ts
packages/proto/build.js
packages/sampling/src/index.ts
packages/sampling/test/dice.test.ts
packages/sampling/test/sampler.test.ts
packages/sdk/test/context.test.ts
packages/solarwinds-apm/package.json
packages/solarwinds-apm/src/processing/parent.ts
packages/solarwinds-apm/src/propagation/headers.ts
packages/solarwinds-apm/src/storage.ts
packages/solarwinds-apm/src/util.ts
packages/solarwinds-apm/test/processing.ts/parent.test.ts
packages/solarwinds-apm/test/propagation/headers.test.ts
packages/solarwinds-apm/test/storage.test.ts
packages/solarwinds-apm/test/util.test.ts
packages/test/package.json
packages/test/src/index.ts
yarn.lock

This adds a set of new utilities, some of them duplicating functionality from existing ones in an improved way. This is because 1. the new pure JS sampler does not have the same requirements as the existing liboboe sampler and 2. a lot of the current utilities were written ~2 years ago before I had much knowledge of OTel JS.
- New span storage/cache which is more flexible and does not require to be cleared manually
- New context utilities which are more flexible
- New parent processor which uses the new span storage and provides better information
- New headers propagator which uses the new context utilities and is cleaner overall
- The test runner now automatically sets up a clean OTel context for each test and provides an API to easily access spans and metrics produced by the test
All …

Better utilities

---

.yarn/versions/9420536b.yml
packages/solarwinds-apm/src/processing/parent-span.ts
packages/solarwinds-apm/src/processing/transaction-name.ts
packages/solarwinds-apm/test/processing/parent-span.test.ts
packages/solarwinds-apm/test/processing/transaction-name.test.ts
packages/solarwinds-apm/test/sampling/grpc.test.ts

No need for a cache or anything like that, we can just directly set the attribute on the parent with the new parent storage.

New transaction name processor

---

.github/workflows/checks.yml
.github/workflows/images.yml
docker/16-amazonlinux2023.Dockerfile
docker/16-ubi8.Dockerfile
docker/16-ubuntu20.04.Dockerfile
docker/18-amazonlinux.Dockerfile
docker/18-ubi.Dockerfile
docker/18-ubuntu.Dockerfile
docker/20-amazonlinux.Dockerfile
docker/20-ubi.Dockerfile
docker/20-ubuntu.Dockerfile
docker/22-alpine.Dockerfile
docker/22-amazonlinux.Dockerfile
docker/22-debian.Dockerfile
docker/22-ubi.Dockerfile
docker/22-ubuntu.Dockerfile
docker/docker-compose.yml

Switches from the EC2 runners to the new GitHub ARM runners. Also add test matrix for Node.js 22, which is the next LTS release.

Use GitHub ARM runners and test on Node 22

---

lambda/package.json
lambda/shim.cjs
lambda/shim.mjs
lambda/wrapper
scripts/lambda.js

This searches for an `@opentelemetry/api` package within the same search paths as the user handler would, and if one is found that's compatible with the library overrides the version we bundle with it.

Use user-provided OTel API whenever possible in Lambda

---

.yarn/versions/e8417283.yml
examples/express-mysql/solarwinds.apm.config.json
lambda/wrapper
packages/instrumentations/package.json
packages/sdk/src/config.ts
packages/sdk/src/otlp-exporter.ts
packages/sdk/src/patches/winston.ts
packages/solarwinds-apm/CONFIGURATION.md
packages/solarwinds-apm/package.json
packages/solarwinds-apm/src/config.ts
packages/solarwinds-apm/src/init.ts
packages/solarwinds-apm/test/config.test.ts
yarn.lock

Follows the same convention as Python with the `SW_APM_EXPORT_LOGS_ENABLED` environment variable and is disabled by default.
As documented at the moment this only works for `winston` but support for more libraries could be added fairly easily.

Support OTLP logs export

---

.yarn/versions/548d9043.yml
examples/next-prisma/package.json
packages/instrumentations/COMPATIBILITY.md
packages/rollup-config/index.js
packages/solarwinds-apm/package.json
packages/solarwinds-apm/src/appoptics/reporter.ts
packages/solarwinds-apm/src/logger.ts
packages/solarwinds-apm/src/metadata.ts
packages/solarwinds-apm/test/appoptics/reporter.test.ts
yarn.lock

Still moving things over with minor changes, this contains the first usage of ESM only features which broke CommonJS builds, so they are disabled now, which is the first step to doing all ESM :)

Move logger and init message logic, stop building CommonJS

---

packages/histogram/src/explicit.ts
packages/histogram/src/exponential.ts
packages/histogram/src/index.ts
packages/solarwinds-apm/package.json
packages/solarwinds-apm/src/appoptics/exporters/metrics.ts
yarn.lock

This histogram code is ported from ingestion, the exporter code is just copied from the existing one.

Update histograms code, move AO metrics exporter to main package

---

.yarn/versions/d5f0cc26.yml
packages/module/src/index.ts
packages/sampling/package.json
packages/sampling/src/sampler.ts
packages/sampling/src/token-bucket.ts
packages/solarwinds-apm/src/config.ts
packages/solarwinds-apm/src/processing/transaction-name.ts
packages/solarwinds-apm/src/sampling/http.ts
yarn.lock

When targettng Node.js, we need to `unref` timers since they are reference counted objects that prevent the runtime from shutting down while they exist. However timers do not have an `unref` method in browsers and attempting to call it there would crash. Instead we make sure that the method exists before calling it (the logic for this is extracted to a utility function).

Remove `unref` calls that would crash in the browser

---

.yarn/versions/39bf73da.yml
packages/instrumentations/COMPATIBILITY.md
packages/instrumentations/package.json
packages/instrumentations/src/index.ts
yarn.lock

This enables some extra contrib detectors by default to detect Kubernetes metadata on AWS EKS and GPC. More generic approach based on the oboe code will follow.

Detect k8s metadata on EKS and GCP

---

.yarn/versions/4fad2c7d.yml
packages/solarwinds-apm/package.json
packages/solarwinds-apm/src/hooks.js
packages/solarwinds-apm/src/index.ts
yarn.lock

This uses a [new feature](https://github.com/nodejs/import-in-the-middle/tree/import-in-the-middle-v1.11.0?tab=readme-ov-file#only-intercepting-hooked-modules) from `import-in-the-middle` to only patch instrumented modules, which fixes issues with Nuxt and potential future issues with other unpatched modules.

Only patch instrumented modules

---

.yarn/versions/f6051174.yml
packages/solarwinds-apm/src/init.ts
packages/solarwinds-apm/src/patches.ts
packages/solarwinds-apm/test/patches.test.ts
yarn.lock

This caused logs to not be send even when `exportLogsEnabled` was set to `true` since the instrumentations themselves were disabled. Also added a lot of tests to cover every case of instrumentation config patching.

Don't disable logging instrumentations when `insertTraceContextIntoLogs` is `false`

---

.yarn/versions/bbf77c3f.yml
packages/solarwinds-apm/src/commonjs/version.js

OTel stopped exporting versions so we read them manually

Properly log library versions

---

.yarn/versions/93ee05f3.yml
packages/solarwinds-apm/src/init.ts
packages/solarwinds-apm/src/patches.ts
packages/solarwinds-apm/test/patches.test.ts

This is a breaking change for the new release. I initially wanted to also use stable only for database attributes but some of the database instrumentations haven't been updated to the new semconv yet so that will have to be in a future release.
We can add more flags to the duplicate list in the future as more of semconv gets stabilized without it being a breaking change.

Migrate to stable semconv for HTTP and set duplicate attributes for others

---

.yarn/versions/b5a12fbf.yml
packages/solarwinds-apm/build.js
packages/solarwinds-apm/build.post.js
packages/solarwinds-apm/package.json
turbo.json

They were being overwritten by `tsc` outputs due to a TypeScript update. Now the manually written version always wins.

Fix CommonJS builds
