solarwinds/apm-js

- packages/sdk/src/patches/bunyan.ts
- packages/sdk/src/patches/index.ts
- packages/sdk/src/patches/pino.ts
- packages/sdk/src/patches/winston.ts
Adds the service name to logs for all supported loggers
> Service name in logs

- .github/workflows/deps.yml
It was missing a proper Node version with corepack and failing
> Fix deps workflow

- .yarn/versions/c2d8fffc.yml
- .yarnrc.yml
- examples/next-prisma/package.json
- examples/package.json
- package.json
- packages/bindings/package.json
- packages/compat/package.json
- packages/dependencies/package.json
- packages/eslint-config/package.json
- packages/histogram/package.json
- packages/lazy/package.json
- packages/merged-config/package.json
- packages/sdk/package.json
- packages/solarwinds-apm/package.json
- scripts/package.json
- yarn.lock
Last step before a first prerelease can be published to npm :tada:
> Update dependencies and mark all packages for initial release

- scripts/version.js
Can confirm that it does work exactly as intended this time 😅
> Fix prerelease script (again)

- .github/workflows/checks.yml
- packages/bindings/npm/linux-arm64-gnu/package.json
- packages/bindings/npm/linux-arm64-musl/package.json
- packages/bindings/npm/linux-x64-gnu/package.json
- packages/bindings/npm/linux-x64-musl/package.json
- packages/bindings/package.json
- packages/compat/package.json
- packages/dependencies/package.json
- packages/eslint-config/package.json
- packages/histogram/package.json
- packages/lazy/package.json
- packages/merged-config/package.json
- packages/sdk/package.json
- packages/solarwinds-apm/package.json
- yarn.lock
@solarwinds-apm/bindings 1.0.0-pre.1, @solarwinds-apm/compat 1.0.0-pre.1, @solarwinds-apm/dependencies 1.0.0-pre.1, @solarwinds-apm/eslint-config 1.0.0-pre.1, @solarwinds-apm/histogram 1.0.0-pre.1, @solarwinds-apm/lazy 1.0.0-pre.1, @solarwinds-apm/merged-config 1.0.0-pre.1, @solarwinds-apm/sdk 1.0.0-pre.1, solarwinds-apm 14.0.0-pre.1
> Initial prerelease

- .github/resources/lockfile-pr-body.md
- .github/workflows/deps.yml
- package.json
Previously used a 3rd party action, now it just uses `git` and `gh`
> Switch deps workflow to using gh

- .github/workflows/checks.yml
- .github/workflows/deps.yml
See https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow for why this is necessary
> Properly trigger checks from deps workflow

- .github/workflows/deps.yml
> Add missing permission to deps workflow

- packages/merged-config/test/index.test.ts
- packages/test/src/index.ts
- yarn.lock
> Update lockfile and fix test wrapper types permanently

- .yarn/versions/35ebe116.yml
- .yarn/versions/a8a0a785.yml
- .yarn/versions/c2d8fffc.yml
- .yarn/versions/ca726d44.yml
- packages/bindings/npm/linux-arm64-gnu/package.json
- packages/bindings/npm/linux-arm64-musl/package.json
- packages/bindings/npm/linux-x64-gnu/package.json
- packages/bindings/npm/linux-x64-musl/package.json
- packages/bindings/package.json
- packages/compat/package.json
- packages/dependencies/package.json
- packages/eslint-config/package.json
- packages/histogram/package.json
- packages/lazy/package.json
- packages/sdk/package.json
- packages/solarwinds-apm/package.json
- packages/test/package.json
New and improved config parsing + other small tweaks
> New prerelease

- .yarn/versions/6d78d10c.yml
- packages/sdk/src/error.ts
- packages/sdk/src/sampler.ts
Now prints status message and warns about auth errors
> Improve sampling decisions error reporting

- .yarn/versions/ec209d7b.yml
- packages/sdk/src/context.ts
- packages/sdk/src/index.ts
- packages/solarwinds-apm/README.md
- packages/solarwinds-apm/src/index.ts
Also documents `setTransactionName`
> Rename and document waitUntilReady

- .yarn/versions/d3b1e5b2.yml
- packages/sdk/src/reporter.ts
- packages/solarwinds-apm/package.json
- packages/solarwinds-apm/src/config.ts
- packages/solarwinds-apm/src/init.ts
- packages/solarwinds-apm/src/peers.ts
- packages/solarwinds-apm/test/config.test.ts
- packages/test/src/bin.ts
- yarn.lock
Adds a new experimental section to the config file with the option
> Support exporting to OTel

- .yarn/versions/3e211bc4.yml
- packages/sdk/src/exporter.ts
- packages/sdk/src/metric-exporter.ts
- packages/solarwinds-apm/src/init.ts
Unsurprisingly exporting from lambda was very shaky
> Properly flush exporters

- .vscode/extensions.json
- .vscode/settings.json
- .vscode/tasks.json
- .yarn/versions/40e8bd64.yml
- packages/bindings/.gitignore
- packages/bindings/build.js
- packages/bindings/package.json
- yarn.lock
Setup VSCode config and recommendations to use clangd for everything C++, set up Prettier as the default formatter for all other languages, add build and test tasks so that the keyboard shortcut for them work.
> Improve DX, especially for C++

- .github/workflows/checks.yml
Should hopefully make it work again
> Use new app for ec2 action

- .yarn/versions/fcb18cfb.yml
- packages/solarwinds-apm/src/config.ts
> Prefer OTEL_SERVICE_NAME over the 2nd half of service key

- .yarn/versions/935256d8.yml
- package.json
- packages/solarwinds-apm/CONFIGURATION.md
- packages/solarwinds-apm/src/config.ts
- packages/solarwinds-apm/test/config.test.ts
> TRUSTED_PATH -> TRUSTEDPATH

- .github/CODEOWNERS
- .github/workflows/checks.yml
- .yarn/versions/d6b17066.yml
- packages/bindings/npm/linux-arm64-gnu/package.json
- packages/bindings/npm/linux-arm64-musl/package.json
- packages/bindings/npm/linux-x64-gnu/package.json
- packages/bindings/npm/linux-x64-musl/package.json
- packages/bindings/package.json
- packages/compat/package.json
- packages/dependencies/package.json
- packages/eslint-config/package.json
- packages/histogram/package.json
- packages/instrumentations/package.json
- packages/lazy/package.json
- packages/module/package.json
- packages/rollup-config/package.json
- packages/sdk/package.json
- packages/solarwinds-apm/package.json
- packages/test/package.json
- yarn.lock
> Finalise move to new org

- .github/workflows/testing.yml
- .yarn/versions/0d3fa678.yml
- docker/otel-collector/config.yml
- examples/express-mysql/package.json
- examples/fastify-postgres/package.json
- examples/hello-distributed/package.json
- examples/hello-manual/package.json
- examples/hello/package.json
- examples/next-prisma/next.config.js
- examples/next-prisma/package.json
- packages/bindings/build.js
- packages/sdk/package.json
- packages/sdk/src/metrics/serverless.ts
- packages/sdk/src/otlp-metrics-exporter.ts
- packages/sdk/src/sampler.ts
- packages/solarwinds-apm/package.json
- packages/solarwinds-apm/src/init.ts
- packages/test/package.json
- scripts/example.js
- yarn.lock
Gonna detail each thing in comments separately since it's a collection of small fixes
> Fix various issues with serverless code

- .yarn/versions/9ee69852.yml
- packages/sdk/src/cache.ts
- packages/sdk/src/config.ts
- packages/sdk/src/context.ts
- packages/sdk/src/exporter.ts
- packages/sdk/src/inbound-metrics-processor.ts
- packages/sdk/src/index.ts
- packages/sdk/src/otlp-exporter.ts
- packages/sdk/src/transaction-name-processor.ts
- packages/sdk/test/cache.test.ts
- packages/sdk/test/context.test.ts
- packages/sdk/test/sampler.test.ts
- packages/sdk/test/transaction-name-processor.test.ts
- packages/solarwinds-apm/CONFIGURATION.md
- packages/solarwinds-apm/src/config.ts
- packages/solarwinds-apm/src/init.ts
The PR title has pretty much all the info
> Transaction names in lambda and SW_APM_TRANSACTION_NAME

- .yarn/versions/d3ea1c90.yml
- packages/sdk/src/config.ts
- packages/sdk/src/reporter.ts
- packages/solarwinds-apm/README.md
- packages/solarwinds-apm/package.json
- packages/solarwinds-apm/src/config.ts
- packages/solarwinds-apm/src/index.es.ts
- packages/solarwinds-apm/test/config.test.ts
- packages/test/src/bin.ts
- yarn.lock
> Support disabling logging

- .yarn/versions/03fbd631.yml
- packages/solarwinds-apm/CHANGELOG.md
- packages/solarwinds-apm/package.json
- packages/solarwinds-apm/src/config.ts
- packages/solarwinds-apm/src/init.ts
Adds a changelog for the v14 prerelease + some more verbose logging at initialisation time.
> Add Changelog

- .yarn/versions/4e73beb6.yml
- packages/sdk/src/otlp-metrics-exporter.ts
> Use delta aggregation for explicit histograms

- lambda/wrapper
Got lost during the copy over but it's a very important one
> Fix missing line in lambda wrapper

- .yarn/versions/9c615a7e.yml
- packages/sdk/src/metrics/serverless.ts
- packages/sdk/src/response-time-processor.ts
Also switch to using single bucket histograms for that metric
> Only send response time metric for servers spans

- .yarn/versions/2372288e.yml
- packages/sdk/src/metrics/serverless.ts
- packages/sdk/src/response-time-processor.ts
See https://github.com/solarwinds/apm-js/pull/286/files#r1525376288
> Fix incorrect response time metric logic

- packages/solarwinds-apm/CONFIGURATION.md
Clarified JSON config limitations and removed unused option.
> NH-73914 config updates

- packages/solarwinds-apm/CONFIGURATION.md
Forgot to actually remove the unused option ;)
> remove metricViews option

- packages/bindings/npm/linux-arm64-gnu-serverless/package.json
- packages/bindings/npm/linux-arm64-gnu/package.json
- packages/bindings/npm/linux-arm64-musl/package.json
- packages/bindings/npm/linux-x64-gnu-serverless/package.json
- packages/bindings/npm/linux-x64-gnu/package.json
- packages/bindings/npm/linux-x64-musl/package.json
- packages/bindings/package.json
- packages/compat/package.json
- packages/dependencies/package.json
- packages/eslint-config/package.json
- packages/histogram/package.json
- packages/instrumentations/package.json
- packages/lazy/package.json
- packages/module/package.json
- packages/proto/package.json
- packages/rollup-config/package.json
- packages/sampling/package.json
- packages/sdk/package.json
- packages/solarwinds-apm/package.json
- packages/test/package.json
All the lambda patches are here !
> 14.0.0-pre.11 prerelease

- .github/workflows/release.yml
> Fix release lambda workflow

- .github/RELEASE.md
- .github/workflows/lambda.yml
- .github/workflows/release.yml
Creates a release draft when running the release CI, following the template with some information pre-filled.
> Create release drafts in CI

- .yarn/versions/a07ff12f.yml
- packages/sdk/src/patches/bunyan.ts
- packages/sdk/src/patches/pino.ts
- packages/sdk/src/patches/winston.ts
- packages/solarwinds-apm/CONFIGURATION.md
Thanks Lin for catching this, every instrumentation supports it now
> Support all instrumented libraries for logs export

- .yarn/versions/7ce04743.yml
- packages/solarwinds-apm/lib.d.ts
- packages/solarwinds-apm/package.json
- packages/solarwinds-apm/src/metrics/runtime.ts
- packages/solarwinds-apm/tsconfig.json
- yarn.lock
This ports the event loop metrics from C++ to JS using new APIs provided by Node. The rest of the code is copied over from its old home in a different package.
> Pure JS runtime metrics

- .yarn/versions/d01421ba.yml
- packages/solarwinds-apm/src/propagation/trace-context.ts
- packages/solarwinds-apm/test/propagation/trace-context.test.ts
Forgot to migrate that logic to the new location with the other propagators. Also added proper testing for it.
> Add missing SW key propagation

- packages/instrumentations/COMPATIBILITY.md
- packages/instrumentations/package.json
- packages/instrumentations/src/compatibility.es.ts
- packages/instrumentations/src/index.ts
- yarn.lock
Now that we can assume an ESM environment this was possible to refactor to be much better and simpler. I also added some newly contributed packages from upstream.
> Optimise instrumentations loading and resource detection.

- .yarn/versions/ee38c44c.yml
- packages/solarwinds-apm/src/appoptics/exporters/traces.ts
- packages/solarwinds-apm/src/appoptics/sampler.ts
- packages/solarwinds-apm/src/propagation/headers.ts
- packages/solarwinds-apm/test/propagation/headers.test.ts
> Add back missing X-Trace header in responses

- .yarn/versions/2b13196a.yml
- packages/solarwinds-apm/package.json
- packages/solarwinds-apm/src/appoptics/reporter.ts
- packages/solarwinds-apm/src/commonjs/version.js
- packages/solarwinds-apm/src/exporters/metrics.ts
- packages/solarwinds-apm/src/metadata.ts
- scripts/docker.js
- yarn.lock
This brings back the fix from #317 to make the liboboe backend not crash
> Add back c-ares name collision mitigation

- .github/workflows/release.yml
- .github/workflows/scan.yml
- .gitignore
- .yarn/versions/b3544001.yml
- package.json
- packages/bindings/npm/linux-arm64-gnu/package.json
- packages/bindings/npm/linux-arm64-musl/package.json
- packages/bindings/npm/linux-x64-gnu/package.json
- packages/bindings/npm/linux-x64-musl/package.json
- packages/bindings/package.json
- packages/dependencies/package.json
- packages/histogram/package.json
- packages/instrumentations/package.json
- packages/module/package.json
- packages/proto/package.json
- packages/sampling/package.json
- packages/solarwinds-apm/package.json
- scripts/lambda.js
- scripts/scan.js
- turbo.json
Adds scripts and actions to run both manually and on release. See [example output](https://my.secure.software/solarwinds/reports/group/c4e85d4d-1ce0-440c-adf3-b7c014e5958e/report/apm-js/solarwinds-apm/15.0.0-pre.1/).
> RL Scanning

- .github/workflows/release.yml
- .github/workflows/testing.yml
- .yarn/versions/b85a12aa.yml
- package.json
- packages/histogram/package.json
- packages/instrumentations/package.json
- packages/sdk/package.json
- packages/solarwinds-apm/CHANGELOG.md
- packages/solarwinds-apm/package.json
- turbo.json
- Update `import-in-the-middle` transitive dependency to fix ESM loader issues.
> solarwinds-apm v14.0.4

- .yarn/versions/1891946b.yml
- packages/instrumentations/package.json
- packages/instrumentations/src/index.ts
- packages/instrumentations/src/resource-detector-uams.ts
- packages/instrumentations/test/resource-detector-uams.test.ts
- packages/instrumentations/test/tsconfig.json
- packages/solarwinds-apm/src/appoptics/exporters/metrics.ts
- yarn.lock
Based on the oboe implementation
> UAMS Client ID detector

- packages/bindings/npm/linux-arm64-gnu/package.json
- packages/bindings/npm/linux-arm64-musl/package.json
- packages/bindings/npm/linux-x64-gnu/package.json
- packages/bindings/npm/linux-x64-musl/package.json
- packages/bindings/package.json
- packages/compat/package.json
- packages/dependencies/package.json
- packages/eslint-config/package.json
- packages/histogram/package.json
- packages/instrumentations/package.json
- packages/module/package.json
- packages/proto/package.json
- packages/sampling/package.json
- packages/solarwinds-apm/package.json
- packages/test/package.json
Service instance and UAMS client detection
> solarwinds-apm v15.0.0-pre.2

- packages/bindings/npm/linux-arm64-gnu/package.json
- packages/bindings/npm/linux-arm64-musl/package.json
- packages/bindings/npm/linux-x64-gnu/package.json
- packages/bindings/npm/linux-x64-musl/package.json
- packages/bindings/package.json
- packages/compat/package.json
- packages/dependencies/package.json
- packages/eslint-config/package.json
- packages/histogram/package.json
- packages/instrumentations/package.json
- packages/module/package.json
- packages/proto/package.json
- packages/sampling/package.json
- packages/solarwinds-apm/package.json
- packages/test/package.json
- No SQLCommenter comments in prepared PostgreSQL queries
- ESM support for AWS Lambda
> solarwinds-apm 15.0.0-pre.3

- .yarn/versions/68ffa503.yml
- packages/solarwinds-apm/src/appoptics/exporters/metrics.ts
- packages/solarwinds-apm/src/exporters/metrics.ts
- packages/solarwinds-apm/test/appoptics/exporters/metrics.test.ts
- packages/solarwinds-apm/test/exporters/metrics.test.ts
Should use cumulative for AO exporter
> Use proper aggregation temporality for gauges

- .yarn/versions/086aaae3.yml
- .yarn/versions/177208c1.yml
- .yarn/versions/2494e310.yml
- .yarn/versions/39bf73da.yml
- .yarn/versions/426feb40.yml
- .yarn/versions/6ef2600a.yml
- .yarn/versions/85dbb913.yml
- .yarn/versions/e762aa43.yml
- packages/compat/package.json
- packages/instrumentations/package.json
- packages/module/package.json
- packages/solarwinds-apm/CHANGELOG.md
- packages/solarwinds-apm/package.json
- packages/solarwinds-apm/src/config.ts
- packages/solarwinds-apm/test/config.test.ts
Resource attribute detections for EKS and GCP. Also experimental web support for internal use.
> solarwinds-apm 15.2.0

- .yarn/versions/23ddbd80.yml
- .yarn/versions/2b77ede8.yml
- .yarn/versions/4202854c.yml
- packages/instrumentations/package.json
- packages/solarwinds-apm/CHANGELOG.md
- packages/solarwinds-apm/package.json
I didn't pull the latest changes from main when creating the 15.3.0 branch 🤦
> solarwinds-apm 15.4.0

- packages/solarwinds-apm/package.json
Fix to only patch instrumented modules
> solarwinds-apm 15.4.1-pre.1

- packages/histogram/package.json
- packages/instrumentations/package.json
- packages/sampling/package.json
- packages/solarwinds-apm/package.json
- packages/test/package.json
@solarwinds-apm/histogram 2.1.0-pre.1, @solarwinds-apm/instrumentations 2.5.0-pre.1, @solarwinds-apm/sampling 3.1.0-pre.1, @solarwinds-apm/test 2.2.0-pre.1, solarwinds-apm 15.5.0-pre.1
> solarwinds-apm 15.5.0-pre.1

- packages/compat/package.json
- packages/histogram/package.json
- packages/instrumentations/package.json
- packages/sampling/package.json
- packages/solarwinds-apm/package.json
- packages/test/package.json
@solarwinds-apm/compat 2.0.2-pre.1, @solarwinds-apm/histogram 2.1.0-pre.2, @solarwinds-apm/instrumentations 2.5.0-pre.2, @solarwinds-apm/sampling 3.1.0-pre.2, @solarwinds-apm/test 2.2.0-pre.2, solarwinds-apm 15.5.0-pre.2
> solarwinds-apm 15.5.0-pre.2

- .yarn/versions/cbae9e69.yml
- packages/solarwinds-apm/src/sampling/http.ts
- packages/solarwinds-apm/test/sampling/http.test.ts
This was inadvertently broken by #603
> Send bearer auth from HTTP sampler

- packages/compat/package.json
- packages/histogram/package.json
- packages/instrumentations/package.json
- packages/sampling/package.json
- packages/solarwinds-apm/package.json
- packages/test/package.json
@solarwinds-apm/compat 2.0.2-pre.2, @solarwinds-apm/histogram 2.1.0-pre.3, @solarwinds-apm/instrumentations 2.5.0-pre.3, @solarwinds-apm/sampling 3.1.0-pre.3, @solarwinds-apm/test 2.2.0-pre.3, solarwinds-apm 15.5.0-pre.3
> solarwinds-apm 15.5.0-pre.3

- packages/compat/package.json
- packages/histogram/package.json
- packages/instrumentations/package.json
- packages/module/package.json
- packages/sampling/package.json
- packages/solarwinds-apm/package.json
- packages/test/package.json
This will likely be the last 15.x release before AO support is removed and runtime metrics are changed to follow semconv
> solarwinds-apm 15.5.0-pre.4

- .github/workflows/checks.yml
- .yarn/versions/fb3ee5e3.yml
- packages/solarwinds-apm/src/commonjs/log.js
- packages/solarwinds-apm/src/commonjs/version.js
Followup to #674 as the checks were accidentally made to always succeed.
> Fix checks and logic for version support

- .yarn/versions/8adf185c.yml
- packages/solarwinds-apm/CONFIGURATION.md
- packages/solarwinds-apm/src/processing/transaction-name.ts
- packages/solarwinds-apm/src/shared/config.ts
- packages/solarwinds-apm/test/config.test.ts
- packages/solarwinds-apm/test/configs/transaction-name.function.js
- packages/solarwinds-apm/test/configs/transaction-name.literal.js
- packages/solarwinds-apm/test/configs/transaction-name.schemes.js
- packages/solarwinds-apm/test/processing/transaction-name.test.ts
This adds support for the `spanAttributes` scheme and for plain functions for more flexibility
> Support declarative transaction naming

- .yarn/versions/f2e75dcb.yml
- packages/solarwinds-apm/src/init.ts
- packages/solarwinds-apm/src/logger.ts
- packages/solarwinds-apm/src/web/init.ts
- packages/solarwinds-apm/src/web/logger.ts
> Obfuscate token in logs
